export interface OldHousehold {
  identification_id?: number;
  structure?: number;
  platform?: number;
  social_center_code?: string;
  agent?: string;
  identification_date_day?: number;
  identification_date_month?: number;
  identification_date_year?: number;
  region?: number;
  department?: number;
  sub_prefecture?: number;
  village?: number;
  neighborhood?: number;
  household_id?: number;
  household_code?: string;
  household_old_code?: string;
  block?: string;
  batch?: string;
  reference?: string;
  marital_status?: string;
  wife_number?: string;
  household_chief_handicap?: string;
  member_number?: string;
  entry_point?: string;
  other_entry_point?: string;
  active_persons_number?: string;
  ovc_number?: string;
  meal_number?: string;
  housing_type?: string;
  other_housing_type?: string;
  room_number?: string;
  house_situation?: string;
  commodity?: string;
  main_water_source?: string;
  other_main_water_source?: string;
  main_electricity_source?: string;
  other_main_electricity_source?: string;
  main_combustible?: string;
  other_main_combustible?: string;
  religion?: string;
  other_religion?: string;
  ethnicity?: string;
  other_household_resource?: string;
  social_capital?: string;
  other_social_capital?: string;
  main_incoming_source?: string;
  other_incoming_source?: string;
  estimated_monthly_expense?: string;
  estimated_monthly_income?: string;
  classification?: string;
  graduation_status?: number;
  registration_status?: number;
  registration_status_change?: number;
  registration_status_report?: number;
  registration_status_remove?: number;
  // members?: Member[];
}

export interface OldHouseholdEvaluation {
    id?: number
    structure?: number
    platform?: number
    cs_code?: string
    household_code?: string
    evaluation1_date?: string
    evaluation2_date?: string
    agent?: string
    region?: number
    department?: number
    sub_prefecture?: number
    commune?: number
    district?: number

    nutritional_security1?: string
    water_accessibility1?: string
    household_health1?: string
    eduction1?: string
    household_income_1?: string
    household_employment_1?: string
    shelter_housing_1?: string
    head_household_1?: string
    protection_1?: string
    
    vulnerability_score_1?: string
    other_score_1?: string
    total_score_1?: number
    category_vulnerability_1?: number
    general_category_1?: number

    nutritional_security_2?: string
    water_accessibility_2?: string
    household_health_2?: string
    eduction_2?: string
    income_household_2?: string
    household_employment_2?: string
    shelter_housing_2?: string
    head_household_2?: string
    protection_2?: string
    
    vulnerability_score_2?: string
    other_score_2?: string
    total_score_2?: string
    vulnerability_category_2?: string
    general_category_2?: string

    registration_status?: string
    registration_status_change?: string
    registration_status_report?: string
    registration_status_remove?: string
    created_by?: number
    created_at?: string
    changed_by?: number
    changed_at?: string
}

export interface OldHouseholdGraduation {
  id?: number;
    structure?: number;
    platform?: number;
    cs_code?: string;
    code_household?: string;
    beneficiary?: number;
    date_evaluation?: string;
    agent?: string;
    care_giver?: string;
    tel_giver?: string;
    advisor?: string;
    advisor_tel?: string;
    region?: number;
    department?: number;
    sub_prefecture?: number;
    commune?: number;
    district?: number;
    response_sit1?: string
    comment_sit_1?: string
    response_sit_2?: string
    comment_sit_2?: string;
    response_sit_3?: string;
    comment_sit_3?: string;
    response_sit_4?: string;
    comment_sit_4?: string;
    response_sit_5?: string;
    comment_sit_5?: string;
    response_sit_6?: string;
    comment_sit_6?: string;
    response_sit_7?: string;
    comment_sit_7?: string;
    response_sit_8?: string;
    comment_sit_8?: string;
    response_sit_9?: string;
    comment_sit_9?: string;
    response_sit_10?: string;
    comment_sit_10?: string;
    response_sit_11?: string;
    comment_sit_11?: string;
    response_sit_12?: string;
    comment_sit_12?: string;
    response_sit_13?: string;
    comment_sit_13?: string;
    response_sit_14?: string;
    comment_sit_14?: string;
    eligibility?: string;
    eligibility_month?: string;
    eligibility_year?: string;
    eligibility_date?: string;
    visitor_eligibility?: string;
    other_visitor?: string;
    creator?: string;
    date_created?: string;
    voice?: string;
    voice_date?: string;
    stat?: number;
    stat_voice?: number;
    stat_status?: number;
    stat_tel?: number;
}

export interface OldHouseholdGraduationService {
  id?: number;
    structure?: number;
    platform?: number;
    cs_code?: string;
    code_household?: string;
    beneficiary?: number;
    date_evaluation?: string;
    agent?: string;
    care_giver?: string;
    tel_giver?: string;
    advisor?: string;
    advisor_tel?: string;
    region?: number;
    department?: number;
    sub_prefecture?: number;
    commune?: number;
    district?: number;
    response_sit1?: string;
    comment_sit_1?: string;
    response_sit_2?: string;
    comment_sit_2?: string;
    response_sit_3?: string;
    comment_sit_3?: string;
    response_sit_4?: string;
    comment_sit_4?: string;
    response_sit_5?: string;
    comment_sit_5?: string;
    response_sit_6?: string;
    comment_sit_6?: string;
    response_sit_7?: string;
    comment_sit_7?: string;
    response_sit_8?: string;
    comment_sit_8?: string;
    response_sit_9?: string;
    comment_sit_9?: string;
    response_sit_10?: string;
    comment_sit_10?: string;
    response_sit_11?: string;
    comment_sit_11?: string;
    response_sit_12?: string;
    comment_sit_12?: string;
    response_sit_13?: string;
    comment_sit_13?: string;
    response_sit_14?: string;
    comment_sit_14?: string;
    eligibility?: string;
    eligibility_month?: string;
    eligibility_year?: string;
    eligibility_date?: string;
    visitor_eligibility?: string;
    other_visitor?: string;
    creator?: string;
    date_created?: string;
    voice?: string;
    voice_date?: string;
    stat?: number;
    stat_voice?: number;
    stat_status?: number;
    stat_tel?: number;
}

export interface OldHouseholdStructure {
  id?: number;
    platform?: number;
    social_center?: string;
    structure?: number;
    code_household?: string;
    region?: string;
    department?: string;
    sub_prefecture?: string;
    commune?: number;
    district?: number;
    agent?: string;
    ilot?: string;
    lot?: string;
    benchmark?: string;
    start_date?: string;
    end_date?: string;
    asset?: string;
    stat_del?: string;
    creator?: string;
    date_created?: string;
    voice?: string;
    voice_date?: string;
}
