export interface Member {
    member_id?: number
    identification_date: string
    order_number?: number
    structure?: number
    platform?: number
    social_center_code?: string
    household_old_code?: string
    household_code?: string
    member_code?: string
    dreams_code?: string
    dreams_date?: string
    household_identification_id?: number
    last_name?: string
    first_name?: string
    gender?: number
    birthdate_month?: number
    birthdate_year?: number
    handicap?: string
    relation_with_chief?: string
    birthdate_certificate?: string
    birthdate_certificate_number?: string
    school_level?: string
    vulnerability?: string
    vulnerability_type?: string
    other_vulnerability_type?: string
    hiv_status?: string
    person_informed?: string
    other_person?: string
    arv_treatment_followup?: string
    care_giver_code?: number
    profession?: string
    needs?: string
    relation_with_adults?: string
    relation_with_children?: string
    relation_with_care_giver?: string
    becoming?: string
    other_becoming?: string
    registration_status?: number
    registration_status_changed?: number
    registration_status_report?: number
    registration_status_remove?: number
}