export interface MemberEvaluation {
    structure?: number
    code_old?: string
    code?: string
    platform?: number
    cs_code?: string
    code_household_old?: string
    code_household?: string
    age?: string
    sex?: string
    evaluation_date_1: string
    evaluation_date_2?: string
    category?: string
    agent?: number
    hiv_status?: string
    eligibility?: string
    region?: number
    department?: number
    sub_prefecture?: number
    commune?: number
    district?: number
    id_num?: number
    code_oev?: number
    code_beneficiary?: string

    nutrition_security?: string
    nutrition_growth?: string
    well_being_health?: string
    health_care?: string
    motor_development?: string
    performance?: string
    education?: string
    dev_educ?: string
    emotion?: number
    social_behavior?: number
    emotional_dev?: number
    gest_fin?: string
    auton?: string
    housing?: number
    care?: number
    abuse?: number
    legal_protection?: number

    nutrition_need?: string
    need_health?: string
    need_educ?: string
    needs_psycho?: string
    needs_renf?: string
    needs_shelter?: string
    need_protection?: string

    nutrition_security_2?: string
    nutrition_growth_2?: string
    well_being_health_2?: string
    health_care_2?: string
    motor_development_2?: string
    performance_2?: string
    education_2?: string
    dev_educ_2?: string
    emotion_2?: string
    social_behavior_2?: string
    emotional_dev_2?: string
    gest_fin_2?: string
    auton_2?: string
    housing_2?: string
    care_2?: string
    abuse_2?: string
    legal_protection_2?: string

    information_source?: string
    other_information_source?: string
    events?: string
    other_event?: string
    comment?: string
    delays_realization_a?: string
    delays_realization_b?: string
    delays_realization_c?: string
    delays_realization_d?: string
    delays_realization_e?: string
    delays_realization_f?: string
    delays_realization_g?: string
    follow_a?: string
    follow_b?: string
    follow_c?: string
    follow_d?: string
    follow_e?: string
    follow_f?: string
    follow_g?: string
}